### A PageRank iteration in Python

![image](pagerank.png)

In [1]:
import numpy as np

In [2]:
# Create the transition matrix
A = np.array([[0.,    0.,    1., 1./2.],
              [1./3., 0.,    0., 0.   ],
              [1./3., 1./2., 0., 1./2.],
              [1./3., 1./2., 0., 0.   ]])

# Add the damping factor
M = 0.85*A + 0.15*(1./4.*np.ones((4,4)))

# Initial set of weights
PR = 1./4.*np.ones((4,1))
PR

array([[ 0.25],
       [ 0.25],
       [ 0.25],
       [ 0.25]])

In [3]:
# First iteration
PR = np.dot(M,PR)
PR

array([[ 0.35625   ],
       [ 0.10833333],
       [ 0.32083333],
       [ 0.21458333]])

In [4]:
# Second iteration
PR = np.dot(M,PR)
PR

array([[ 0.40140625],
       [ 0.1384375 ],
       [ 0.27567708],
       [ 0.18447917]])

In [5]:
# Third iteration
PR = np.dot(M,PR)
PR

array([[ 0.35022917],
       [ 0.15123177],
       [ 0.28847135],
       [ 0.21006771]])

### Iteration until convergence

In [6]:
epsylon = 0.01
iterations = 0
PR = 1./4.*np.ones((4,1))
oldPR = np.zeros((4,1))
while max(np.abs(oldPR-PR)) > epsylon:
    oldPR = PR
    PR = np.dot(M,PR)
    iterations +=1
print("PR after",iterations,"iterations:")
print(PR)

PR after 5 iterations:
[[ 0.36966846]
 [ 0.14289417]
 [ 0.28643227]
 [ 0.2010051 ]]
